spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=${DB_USE_SSL}
    username: ${DB_USER}
    password: ${DB_PWD}
  mail:
    username: ${MAIL_USER}
    password: ${MAIL_PWD}
    host: ${MAIL_SERVER}
    port: ${MAIL_PORT}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH}
          starttls:
            enable: ${ENABLE_TLS}
          ssl:
            enable: ${ENABLE_SSL}
            protocols: ${MAIL_SSL_PROTOCOLS}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: ERROR
      springframework:
        boot:
          autoconfigure: ERROR
jwt:
  secret: ${JWT_SECRET}
  expire: ${JWT_EXPIRE}
